#!/bin/bash -l
#SBATCH -N 1                # you'll never need more than 1 node for the serial code
#SBATCH -n 20				# number of processes
#SBATCH -t 00:20:00         # adjust the amount of time as necessary
#SBATCH -J auto-openmp32
#SBATCH -o auto-openmp32.%j.stdout
#SBATCH -p gpu
#SBATCH -A UH-COSC6374-18F-Para

rm openmp.txt
./serial -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=1
./openmp -p 1 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=2
./openmp -p 2 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=12
./openmp -p 12 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=18
./openmp -p 18 -n 500 -no -s openmp.txt
export OMP_NUM_THREADS=20
./openmp -p 20 -n 500 -no -s openmp.txt

export OMP_NUM_THREADS=2
./openmp -p 2 -n 1000 -no -s openmp.txt
export OMP_NUM_THREADS=4
./openmp -p 4 -n 2000 -no -s openmp.txt
export OMP_NUM_THREADS=6
./openmp -p 6 -n 3000 -no -s openmp.txt
export OMP_NUM_THREADS=12
./openmp -p 12 -n 6000 -no -s openmp.txt
export OMP_NUM_THREADS=18
./openmp -p 18 -n 9000 -no -s openmp.txt
export OMP_NUM_THREADS=20
./openmp -p 20 -n 12000 -no -s openmp.txt

./autograder -v openmp -s openmp.txt
